name: 🐛 Bug Report
description: Wechaty问题反馈
title: "[Bug]: "
labels: bug
body: 
  - type: textarea
    attributes:
      label: Environment
      description: |
        * please give the following wechaty related package info:
          ```sh
          pip list | grep paddle
          ```
        * the type of token do you use
        * the version of wechaty docker gateway
      value: |
          - wechaty:
          - wechaty-puppet: 
          - wechaty-puppet-service: 
          - wechaty-plugin-contrib: 
          - token type: padlocal|wxwork|xp
          - the version of wechaty docker container: [0.65]
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        please post a detailed description for your issue, you can use the text or screen-shot to show your errors.
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimum reproducible code
      description: please give the minimum code which can reproduce the issue you describe, so that we can help you fix the issue quickly.
    validations:
      required: true